---
defaults: &defaults
  alpha: null
  background: null
  define: null
  extent: null
  gravity: null
  resize: null
  size: null
.svg:
  .png:
    <<: *defaults
    background: :background
    extent: :auto
    gravity: center
    resize:
    size: :auto
  .ico:
    <<: *defaults
    background: :background
    define:
    extent: :auto
    gravity: center
    resize:
    size: :auto
  .svg:
    <<: *defaults
.png:
  .ico:
    <<: *defaults
    background: :background
    define:
    extent: :auto
    gravity: center
    resize:
  .png:
    <<: *defaults
    background: :background
    extent: :auto
    gravity: center
    resize:
